### ISSUE TITLE
PARSE ERROR! Unexpected char: -

### ISSUE THREAD

**Issue by Annlean** [jezberg/loandra#8]
Hello!
When I use Loandra to solve a instance with negative literals, it reports “PARSE ERROR! Unexpected char: -”. I use default command line "./loandra test.cnf" and the content of the test.cnf is 
"p cnf 7 7
-1 2 0
-2 3 0
-3 1 0
2 7 6 0
2 -7 -6 0
-6 7 0
-7 6 0"
If the instance does not have negative literals, it solves normally. It seems that there is a problem when parsing the CNF file or maybe I used an incorrect command. Please help to solve this ERROR. Thanks!

**Comment by jezberg** [comment]
Hi
Thanks for your interest!

This is a very old file format for MaxSAT, which was used for the so-called unweighted non-partial MaxSAT problem in which you do not have hard clauses, and every soft clause has weight 1". The format is not properly supported, and I do not want to support it since it's ambiguous in the sense that the files look exactly like the CNF file format used in SAT solving. 
For details on the most preferred format, please see https://maxsat-evaluations.github.io/2024/rules.html#input.

The behavior you see arises from the solver considering the first integer on each line as the weight of the soft clause and throwing an error when the weight is negative. 

For solving unweighted non-partial MaxSAT the fix is to add a weight of 1 in front of every line and remove the line starting with "p" i.e., the file should look like
"1 -1 2 0
1 -2 3 0
1 -3 1 0
1 2 7 6 0
1 2 -7 -6 0
1 -6 7 0"
with this, you should not use the -old-format command line argument. 

If you instead are solving the SAT problem, i.e., only want to find an assignment that satisfies all clauses or prove that one does not exist, you should instead consider a dedicated SAT solver (e.g. https://github.com/arminbiere/cadical) 

Your comment made me realize that the error message should be more descriptive. Thank you for that. I will change the behavior to be more helpful shortly.
